stages:
  - build
  # - deploy

services:
  - docker:24.0.6-dind

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  ENVIRONMENT: "build"
  SHARED_PATH: /builds/$CI_PROJECT_PATH/shared
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"
  DOCKER_REGISTRY: 
  REGISTRY_PROJECT: codabench
  REGISTRY_USER: 
  REGISTRY_TOKEN: 

# frontend
build:
  image: docker:24.0.6
  tags:
    - docker
    - ubuntu
  stage: build
  script:
    - docker build . -t ${DOCKER_REGISTRY}/${REGISTRY_PROJECT}/humaneval:${CI_COMMIT_REF_NAME}
    - echo "Deploy deeplab"
    - echo $REGISTRY_TOKEN
    - echo "$REGISTRY_TOKEN"| docker login ${DOCKER_REGISTRY} --username $REGISTRY_USER --password-stdin
    - echo "Pushing ${DOCKER_REGISTRY}/${REGISTRY_PROJECT}/humaneval:${CI_COMMIT_REF_NAME}"
    - docker push ${DOCKER_REGISTRY}/${REGISTRY_PROJECT}/humaneval:${CI_COMMIT_REF_NAME}

